name: Binary compatibility verification (for API)

on:
  push:
    paths:
      - 'scalabot-meta/**'
      - 'scalabot-extension/**'
  pull_request:
    paths:
      - 'scalabot-meta/**'
      - 'scalabot-extension/**'

permissions:
  contents: read

jobs:
  apiCompatibilityCheck:
    timeout-minutes: 8
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt-hotspot'
          cache: 'gradle'
      - uses: gradle/wrapper-validation-action@v1
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and run binary compatibility verification
        uses: gradle/gradle-build-action@v3.1.0
        with:
          gradle-version: 'wrapper'
          arguments: apiCheck
